apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rg-python-refresh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rgangadharan2510/git-learn.git
    targetRevision: main
    path: shs-argocd/apps/rg-python-minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
