kind: List
apiVersion: v1
items:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: qualys-secrets
      namespace: qualys
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      encryptedData:
        ACTIVATIONID: AgC3fL9wApFZt7mSgkbCYfGbHGqX+h7I3Hd3gtN1ewDkdndLTclHcw7OUeYCSVGB5VjIN+9nv7e0qXJW+h9t3iYpavRy+PJBH7TJJSI3xXGcxA6OkqQifjPVA9M1lrjUKnMCnbPxqCQ83oaZoHI5f4meaj+n+Evt4vHZd2efkSDgqBLy951mc+GDcbehleLmpfNznYB0CV0g6AgxqFPWrPGiAcVrpjOzM0sru2oAOjB6ub5qdq7RSb8BEZ6k13I+P8qCFZvz040Pv1twAJg/8pbf17wlm8C68N9b/BNj52nlY7mFU9Foogusl/zs51YXTk5CvCnpjJRYK6WcCa5OPMPSsh/Y7PRn7YdjEoK8Hua2ReBZYn279aXDJdIDtyV+U9REZMizDBHswktHAqaRtYiMLCJBGeQ+nvpbnETXXdYNCofNcQF4zS2qV5/Ub90tYpbQ3AGSwzr5AbyCxNCejMTvX3hpDDzeoEHW+D371CY/97L8emAwbGVuIlLxkpflApbTUs/Pz5W6Alzs9GJdNgjTP/EhHUXnj+XSwoqrZVpbvnBDZ3As/j0RoNOBzea7o0J5QggqG27fVkgRnQs1AckpCymm/Z5DIzMRcvgQ5igIgPQuonwaQZavYGTjshjJsAqEZ+uTJg2YjAUWghI8ttKUtHPU6Ut64xJoS+dxHeCDLl2rnL/ioJRiu9H32uz8Cl3JckD2rQXMJ2qbBNvqnacsUmWyd6LV6WNcTru2KG8yYSj68R4=
        CUSTOMERID: AgCXw6LrcuseO8wgvZo5jEfjCWJTg/Pg/nZLz5aY/lo79Wj9xmoyON40wFr8/nuVVch4f1pEBxQZZEVvRB7hN0ld42vf3Ywzy5gOKBHUwg4AG07ZtZMdRVwyi1bQTswkRiI+CNyoUWWZ2vLrkrx+0QpZHtMuz0GAkR8cffHpoVcnIpdO77R703geyBJ8K5uP0lNnww6mzYZ5rhFu9pW8GDhUH1m/6+Un7+0aM5ulixXpdHJmZ8jwFM7mfMSAs5xfqF0xMq0Ouy2AAk2Vq5LdrfVALndRZyrk2zdFnD3B4K52pZP0mI/cm3rL+KGybqe1TB8jo7m3P8VpT6UwF636JfBCAwN6V8WKbK17CRG3ZIHdhFrUxJU/nJVDufd5Ff0ALxMvwbgBY0rqcmJKKJ/fk0PqL+EeTBw0Q9TkGg18Hd/dKJw9E/A5LBphDcb1QEB064wahY3gsGAb+O2JTGSj6TTLOEuROCfR93Pj2kMHWOMT91n0+y/hwh0FzLwGrxZLfWDfM0rAXUlIzLQGie7t4CDSZ7qQSYot6GXfWtwqYQrRuzqCl2h0bw6LZXW/X2TtdrglYvNOfAAwT6waY8APSh9gg6UVnWGYyEGXENjSYqXfe4X1TRd73EjZadYMVt/mbHdyYl02d2IJ+OHOJhfRiI85lXLkiaHaGQQcyezYoyjGxchT4oaT8RrcmLbQ1XzbJIsvWCCHwzdiPbsxJJtQox0Rh9j+rdFaF1Qj0V4MGH2BTWZ+eNU=
      template:
        metadata:
          creationTimestamp: null
          name: qualys-secrets
          namespace: qualys
        type: Opaque