apiVersion: apps/v1
kind: Deployment
metadata:
  name: rg-python-refresh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rg-python-refresh
  template:
    metadata:
      labels:
        app: rg-python-refresh
    spec:
      containers:
        - name: rg-python-refresh
          image: 257676781382.dkr.ecr.us-east-2.amazonaws.com/rg-python-refresh:latest
          imagePullPolicy: Always
          args: ["--download"]
          env:
            - name: S3_BUCKET
              value: "rg-python-refresh"
          volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws
          readOnly: true
      volumes:
      - name: aws-credentials
        hostPath:
          path: /home/rgangad/.aws
          type: Directory
            #- name: AWS_ACCESS_KEY_ID
            #  valueFrom:
            #    secretKeyRef:
            #      name: aws-secret
            #      key: AWS_ACCESS_KEY_ID
            #- name: AWS_SECRET_ACCESS_KEY
            #  valueFrom:
            #    secretKeyRef:
            #      name: aws-secret
            #      key: AWS_SECRET_ACCESS_KEY
            #- name: AWS_DEFAULT_REGION
            #  valueFrom:
            #    secretKeyRef:
            #      name: aws-secret
            #      key: AWS_DEFAULT_REGION
  
      imagePullSecrets:
         - name: ecr-secret
      









